<?php

/*
 * This file is part of the Telltale package.
 *
 * (c) Renan de Lima <renandelima@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace TelltaleTest\Report;

/**
 * @covers Telltale\Agent\AbstractTraceAgent
 */
class AbstractTraceAgentTest extends \PHPUnit_Framework_TestCase
{
    public function testTraceFileGenerated()
    {
        $agent = $this->getMockForAbstractClass('Telltale\\Agent\\AbstractTraceAgent');
        $agent->start();
        $agent->stop();

        $reflection = new \ReflectionClass($agent);
        $attribute = $reflection->getProperty('traceFile');
        $attribute->setAccessible(true);
        $file = $attribute->getValue($agent);

        $lines = file($file);
        $this->assertEquals(
            "File format: 2\n",
            $lines[1],
            'Trace file generated by AbstractTraceAgent is not valid.'
        );
    }
}
